services:
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
    environment:
      - NGINX_SERVER_NAME=${NGINX_SERVER_NAME:-localhost}
      - SSL_CERT_PATH=/etc/letsencrypt/live/${NGINX_SERVER_NAME:-localhost}/fullchain.pem
      - SSL_CERT_KEY_PATH=/etc/letsencrypt/live/${NGINX_SERVER_NAME:-localhost}/privkey.pem
    depends_on:
      - app

  app:
    build:
      context: ./docker/php
    volumes:
      - ./src:/var/www/html
    depends_on:
      - postgresql

  postgresql:
    build:
      context: ./docker/postgresql
    environment:
      POSTGRES_DB: ${DB_DATABASE:-kabu_dash}
      POSTGRES_USER: ${DB_USERNAME:-kabu_dash}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - pgdata:/var/lib/postgresql/data

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
    profiles:
      - certbot

volumes:
  pgdata:
